// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file thru/core/v1/account.proto (package thru.core.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { Pubkey } from "../../common/v1/primitives_pb";
import { ConsensusStatus } from "../../common/v1/consensus_pb";

/**
 * AccountView controls which sections of account resources are returned.
 *
 * @generated from enum thru.core.v1.AccountView
 */
export enum AccountView {
  /**
   * ACCOUNT_VIEW_UNSPECIFIED uses service defaults.
   *
   * @generated from enum value: ACCOUNT_VIEW_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * ACCOUNT_VIEW_PUBKEY_ONLY returns only the account address.
   *
   * @generated from enum value: ACCOUNT_VIEW_PUBKEY_ONLY = 1;
   */
  PUBKEY_ONLY = 1,

  /**
   * ACCOUNT_VIEW_META_ONLY returns only account metadata.
   *
   * @generated from enum value: ACCOUNT_VIEW_META_ONLY = 2;
   */
  META_ONLY = 2,

  /**
   * ACCOUNT_VIEW_DATA_ONLY returns only account data.
   *
   * @generated from enum value: ACCOUNT_VIEW_DATA_ONLY = 3;
   */
  DATA_ONLY = 3,

  /**
   * ACCOUNT_VIEW_FULL returns address, metadata, and data.
   *
   * @generated from enum value: ACCOUNT_VIEW_FULL = 4;
   */
  FULL = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(AccountView)
proto3.util.setEnumType(AccountView, "thru.core.v1.AccountView", [
  { no: 0, name: "ACCOUNT_VIEW_UNSPECIFIED" },
  { no: 1, name: "ACCOUNT_VIEW_PUBKEY_ONLY" },
  { no: 2, name: "ACCOUNT_VIEW_META_ONLY" },
  { no: 3, name: "ACCOUNT_VIEW_DATA_ONLY" },
  { no: 4, name: "ACCOUNT_VIEW_FULL" },
]);

/**
 * AccountFlags enumerates boolean account capability flags.
 *
 * @generated from message thru.core.v1.AccountFlags
 */
export class AccountFlags extends Message<AccountFlags> {
  /**
   * @generated from field: bool is_program = 1;
   */
  isProgram = false;

  /**
   * @generated from field: bool is_privileged = 2;
   */
  isPrivileged = false;

  /**
   * @generated from field: bool is_uncompressable = 3;
   */
  isUncompressable = false;

  /**
   * @generated from field: bool is_ephemeral = 4;
   */
  isEphemeral = false;

  /**
   * @generated from field: bool is_deleted = 5;
   */
  isDeleted = false;

  /**
   * @generated from field: bool is_new = 6;
   */
  isNew = false;

  /**
   * @generated from field: bool is_compressed = 7;
   */
  isCompressed = false;

  constructor(data?: PartialMessage<AccountFlags>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.AccountFlags";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "is_program", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "is_privileged", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "is_uncompressable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "is_ephemeral", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "is_deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "is_new", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "is_compressed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AccountFlags {
    return new AccountFlags().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AccountFlags {
    return new AccountFlags().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AccountFlags {
    return new AccountFlags().fromJsonString(jsonString, options);
  }

  static equals(a: AccountFlags | PlainMessage<AccountFlags> | undefined, b: AccountFlags | PlainMessage<AccountFlags> | undefined): boolean {
    return proto3.util.equals(AccountFlags, a, b);
  }
}

/**
 * AccountMeta captures metadata associated with an account.
 *
 * @generated from message thru.core.v1.AccountMeta
 */
export class AccountMeta extends Message<AccountMeta> {
  /**
   * @generated from field: uint32 version = 1;
   */
  version = 0;

  /**
   * @generated from field: thru.core.v1.AccountFlags flags = 2;
   */
  flags?: AccountFlags;

  /**
   * @generated from field: uint32 data_size = 3;
   */
  dataSize = 0;

  /**
   * Account sequence number
   *
   * @generated from field: uint64 seq = 4;
   */
  seq = protoInt64.zero;

  /**
   * @generated from field: thru.common.v1.Pubkey owner = 5;
   */
  owner?: Pubkey;

  /**
   * @generated from field: uint64 balance = 6;
   */
  balance = protoInt64.zero;

  /**
   * @generated from field: uint64 nonce = 7;
   */
  nonce = protoInt64.zero;

  constructor(data?: PartialMessage<AccountMeta>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.AccountMeta";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "version", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "flags", kind: "message", T: AccountFlags },
    { no: 3, name: "data_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "seq", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "owner", kind: "message", T: Pubkey },
    { no: 6, name: "balance", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "nonce", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AccountMeta {
    return new AccountMeta().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AccountMeta {
    return new AccountMeta().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AccountMeta {
    return new AccountMeta().fromJsonString(jsonString, options);
  }

  static equals(a: AccountMeta | PlainMessage<AccountMeta> | undefined, b: AccountMeta | PlainMessage<AccountMeta> | undefined): boolean {
    return proto3.util.equals(AccountMeta, a, b);
  }
}

/**
 * AccountData contains account data payloads.
 *
 * @generated from message thru.core.v1.AccountData
 */
export class AccountData extends Message<AccountData> {
  /**
   * @generated from field: optional bytes data = 1;
   */
  data?: Uint8Array;

  /**
   * @generated from field: optional bool compressed = 2;
   */
  compressed?: boolean;

  /**
   * @generated from field: optional string compression_algorithm = 3;
   */
  compressionAlgorithm?: string;

  constructor(data?: PartialMessage<AccountData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.AccountData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true },
    { no: 2, name: "compressed", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 3, name: "compression_algorithm", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AccountData {
    return new AccountData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AccountData {
    return new AccountData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AccountData {
    return new AccountData().fromJsonString(jsonString, options);
  }

  static equals(a: AccountData | PlainMessage<AccountData> | undefined, b: AccountData | PlainMessage<AccountData> | undefined): boolean {
    return proto3.util.equals(AccountData, a, b);
  }
}

/**
 * DataSlice describes a contiguous range of account data to return.
 *
 * @generated from message thru.core.v1.DataSlice
 */
export class DataSlice extends Message<DataSlice> {
  /**
   * @generated from field: uint32 offset = 1;
   */
  offset = 0;

  /**
   * @generated from field: uint32 length = 2;
   */
  length = 0;

  constructor(data?: PartialMessage<DataSlice>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.DataSlice";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "offset", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "length", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DataSlice {
    return new DataSlice().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DataSlice {
    return new DataSlice().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DataSlice {
    return new DataSlice().fromJsonString(jsonString, options);
  }

  static equals(a: DataSlice | PlainMessage<DataSlice> | undefined, b: DataSlice | PlainMessage<DataSlice> | undefined): boolean {
    return proto3.util.equals(DataSlice, a, b);
  }
}

/**
 * AccountPage represents a 4KB chunk for streaming account data.
 *
 * @generated from message thru.core.v1.AccountPage
 */
export class AccountPage extends Message<AccountPage> {
  /**
   * @generated from field: uint32 page_idx = 1;
   */
  pageIdx = 0;

  /**
   * @generated from field: uint32 page_size = 2;
   */
  pageSize = 0;

  /**
   * @generated from field: bytes page_data = 3;
   */
  pageData = new Uint8Array(0);

  /**
   * @generated from field: optional bool compressed = 4;
   */
  compressed?: boolean;

  /**
   * @generated from field: optional string compression_algorithm = 5;
   */
  compressionAlgorithm?: string;

  constructor(data?: PartialMessage<AccountPage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.AccountPage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page_idx", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "page_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "page_data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "compressed", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 5, name: "compression_algorithm", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AccountPage {
    return new AccountPage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AccountPage {
    return new AccountPage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AccountPage {
    return new AccountPage().fromJsonString(jsonString, options);
  }

  static equals(a: AccountPage | PlainMessage<AccountPage> | undefined, b: AccountPage | PlainMessage<AccountPage> | undefined): boolean {
    return proto3.util.equals(AccountPage, a, b);
  }
}

/**
 * VersionContextMetadata captures context for a returned account state.
 *
 * @generated from message thru.core.v1.VersionContextMetadata
 */
export class VersionContextMetadata extends Message<VersionContextMetadata> {
  /**
   * @generated from field: optional uint64 slot = 1;
   */
  slot?: bigint;

  /**
   * @generated from field: optional google.protobuf.Timestamp block_timestamp = 2;
   */
  blockTimestamp?: Timestamp;

  constructor(data?: PartialMessage<VersionContextMetadata>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.VersionContextMetadata";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "slot", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 2, name: "block_timestamp", kind: "message", T: Timestamp, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VersionContextMetadata {
    return new VersionContextMetadata().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VersionContextMetadata {
    return new VersionContextMetadata().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VersionContextMetadata {
    return new VersionContextMetadata().fromJsonString(jsonString, options);
  }

  static equals(a: VersionContextMetadata | PlainMessage<VersionContextMetadata> | undefined, b: VersionContextMetadata | PlainMessage<VersionContextMetadata> | undefined): boolean {
    return proto3.util.equals(VersionContextMetadata, a, b);
  }
}

/**
 * Account models a fully decoded account resource.
 *
 * @generated from message thru.core.v1.Account
 */
export class Account extends Message<Account> {
  /**
   * @generated from field: thru.common.v1.Pubkey address = 1;
   */
  address?: Pubkey;

  /**
   * @generated from field: optional thru.core.v1.AccountMeta meta = 2;
   */
  meta?: AccountMeta;

  /**
   * @generated from field: optional thru.core.v1.AccountData data = 3;
   */
  data?: AccountData;

  /**
   * @generated from field: optional thru.core.v1.VersionContextMetadata version_context = 4;
   */
  versionContext?: VersionContextMetadata;

  /**
   * @generated from field: optional thru.common.v1.ConsensusStatus consensus_status = 5;
   */
  consensusStatus?: ConsensusStatus;

  constructor(data?: PartialMessage<Account>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.Account";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "address", kind: "message", T: Pubkey },
    { no: 2, name: "meta", kind: "message", T: AccountMeta, opt: true },
    { no: 3, name: "data", kind: "message", T: AccountData, opt: true },
    { no: 4, name: "version_context", kind: "message", T: VersionContextMetadata, opt: true },
    { no: 5, name: "consensus_status", kind: "enum", T: proto3.getEnumType(ConsensusStatus), opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Account {
    return new Account().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Account {
    return new Account().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Account {
    return new Account().fromJsonString(jsonString, options);
  }

  static equals(a: Account | PlainMessage<Account> | undefined, b: Account | PlainMessage<Account> | undefined): boolean {
    return proto3.util.equals(Account, a, b);
  }
}

/**
 * RawAccount captures raw serialized account bytes.
 *
 * @generated from message thru.core.v1.RawAccount
 */
export class RawAccount extends Message<RawAccount> {
  /**
   * @generated from field: thru.common.v1.Pubkey address = 1;
   */
  address?: Pubkey;

  /**
   * @generated from field: bytes raw_meta = 2;
   */
  rawMeta = new Uint8Array(0);

  /**
   * @generated from field: optional bytes raw_data = 3;
   */
  rawData?: Uint8Array;

  /**
   * @generated from field: optional thru.core.v1.VersionContextMetadata version_context = 4;
   */
  versionContext?: VersionContextMetadata;

  constructor(data?: PartialMessage<RawAccount>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.RawAccount";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "address", kind: "message", T: Pubkey },
    { no: 2, name: "raw_meta", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 3, name: "raw_data", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true },
    { no: 4, name: "version_context", kind: "message", T: VersionContextMetadata, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RawAccount {
    return new RawAccount().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RawAccount {
    return new RawAccount().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RawAccount {
    return new RawAccount().fromJsonString(jsonString, options);
  }

  static equals(a: RawAccount | PlainMessage<RawAccount> | undefined, b: RawAccount | PlainMessage<RawAccount> | undefined): boolean {
    return proto3.util.equals(RawAccount, a, b);
  }
}

