// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file thru/core/v1/block.proto (package thru.core.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { BlockHash } from "./types_pb";
import { Pubkey, Signature } from "../../common/v1/primitives_pb";
import { ConsensusStatus } from "../../common/v1/consensus_pb";

/**
 * BlockView controls how much of a block resource is returned.
 *
 * @generated from enum thru.core.v1.BlockView
 */
export enum BlockView {
  /**
   * @generated from enum value: BLOCK_VIEW_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: BLOCK_VIEW_HEADER_ONLY = 1;
   */
  HEADER_ONLY = 1,

  /**
   * @generated from enum value: BLOCK_VIEW_HEADER_AND_FOOTER = 2;
   */
  HEADER_AND_FOOTER = 2,

  /**
   * @generated from enum value: BLOCK_VIEW_BODY_ONLY = 3;
   */
  BODY_ONLY = 3,

  /**
   * @generated from enum value: BLOCK_VIEW_FULL = 4;
   */
  FULL = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(BlockView)
proto3.util.setEnumType(BlockView, "thru.core.v1.BlockView", [
  { no: 0, name: "BLOCK_VIEW_UNSPECIFIED" },
  { no: 1, name: "BLOCK_VIEW_HEADER_ONLY" },
  { no: 2, name: "BLOCK_VIEW_HEADER_AND_FOOTER" },
  { no: 3, name: "BLOCK_VIEW_BODY_ONLY" },
  { no: 4, name: "BLOCK_VIEW_FULL" },
]);

/**
 * ExecutionStatus enumerates block execution results.
 *
 * @generated from enum thru.core.v1.ExecutionStatus
 */
export enum ExecutionStatus {
  /**
   * @generated from enum value: EXECUTION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: EXECUTION_STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: EXECUTION_STATUS_EXECUTED = 2;
   */
  EXECUTED = 2,

  /**
   * @generated from enum value: EXECUTION_STATUS_FAILED = 3;
   */
  FAILED = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(ExecutionStatus)
proto3.util.setEnumType(ExecutionStatus, "thru.core.v1.ExecutionStatus", [
  { no: 0, name: "EXECUTION_STATUS_UNSPECIFIED" },
  { no: 1, name: "EXECUTION_STATUS_PENDING" },
  { no: 2, name: "EXECUTION_STATUS_EXECUTED" },
  { no: 3, name: "EXECUTION_STATUS_FAILED" },
]);

/**
 * BlockHeader describes metadata about a block.
 *
 * @generated from message thru.core.v1.BlockHeader
 */
export class BlockHeader extends Message<BlockHeader> {
  /**
   * @generated from field: uint64 slot = 1;
   */
  slot = protoInt64.zero;

  /**
   * @generated from field: thru.core.v1.BlockHash block_hash = 2;
   */
  blockHash?: BlockHash;

  /**
   * @generated from field: thru.common.v1.Signature header_signature = 3;
   */
  headerSignature?: Signature;

  /**
   * @generated from field: uint32 version = 4;
   */
  version = 0;

  /**
   * @generated from field: thru.common.v1.Pubkey producer = 5;
   */
  producer?: Pubkey;

  /**
   * @generated from field: google.protobuf.Timestamp expiry_timestamp = 6;
   */
  expiryTimestamp?: Timestamp;

  /**
   * @generated from field: uint64 start_slot = 7;
   */
  startSlot = protoInt64.zero;

  /**
   * @generated from field: uint32 expiry_after = 8;
   */
  expiryAfter = 0;

  /**
   * @generated from field: uint32 max_block_size = 9;
   */
  maxBlockSize = 0;

  /**
   * @generated from field: uint64 max_compute_units = 10;
   */
  maxComputeUnits = protoInt64.zero;

  /**
   * @generated from field: uint32 max_state_units = 11;
   */
  maxStateUnits = 0;

  /**
   * @generated from field: uint64 price = 12;
   */
  price = protoInt64.zero;

  /**
   * @generated from field: google.protobuf.Timestamp block_time = 13;
   */
  blockTime?: Timestamp;

  constructor(data?: PartialMessage<BlockHeader>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.BlockHeader";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "slot", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "block_hash", kind: "message", T: BlockHash },
    { no: 3, name: "header_signature", kind: "message", T: Signature },
    { no: 4, name: "version", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 5, name: "producer", kind: "message", T: Pubkey },
    { no: 6, name: "expiry_timestamp", kind: "message", T: Timestamp },
    { no: 7, name: "start_slot", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 8, name: "expiry_after", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 9, name: "max_block_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 10, name: "max_compute_units", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 11, name: "max_state_units", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 12, name: "price", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 13, name: "block_time", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BlockHeader {
    return new BlockHeader().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BlockHeader {
    return new BlockHeader().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BlockHeader {
    return new BlockHeader().fromJsonString(jsonString, options);
  }

  static equals(a: BlockHeader | PlainMessage<BlockHeader> | undefined, b: BlockHeader | PlainMessage<BlockHeader> | undefined): boolean {
    return proto3.util.equals(BlockHeader, a, b);
  }
}

/**
 * BlockFooter captures execution result metadata for a block.
 *
 * @generated from message thru.core.v1.BlockFooter
 */
export class BlockFooter extends Message<BlockFooter> {
  /**
   * @generated from field: thru.common.v1.Signature signature = 1;
   */
  signature?: Signature;

  /**
   * @generated from field: thru.core.v1.ExecutionStatus status = 2;
   */
  status = ExecutionStatus.UNSPECIFIED;

  /**
   * @generated from field: uint64 consumed_compute_units = 3;
   */
  consumedComputeUnits = protoInt64.zero;

  /**
   * @generated from field: uint32 consumed_state_units = 4;
   */
  consumedStateUnits = 0;

  constructor(data?: PartialMessage<BlockFooter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.BlockFooter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "signature", kind: "message", T: Signature },
    { no: 2, name: "status", kind: "enum", T: proto3.getEnumType(ExecutionStatus) },
    { no: 3, name: "consumed_compute_units", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "consumed_state_units", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BlockFooter {
    return new BlockFooter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BlockFooter {
    return new BlockFooter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BlockFooter {
    return new BlockFooter().fromJsonString(jsonString, options);
  }

  static equals(a: BlockFooter | PlainMessage<BlockFooter> | undefined, b: BlockFooter | PlainMessage<BlockFooter> | undefined): boolean {
    return proto3.util.equals(BlockFooter, a, b);
  }
}

/**
 * Block represents a fully decoded block resource.
 *
 * @generated from message thru.core.v1.Block
 */
export class Block extends Message<Block> {
  /**
   * @generated from field: thru.core.v1.BlockHeader header = 1;
   */
  header?: BlockHeader;

  /**
   * @generated from field: optional thru.core.v1.BlockFooter footer = 2;
   */
  footer?: BlockFooter;

  /**
   * @generated from field: optional bytes body = 3;
   */
  body?: Uint8Array;

  /**
   * @generated from field: optional thru.common.v1.ConsensusStatus consensus_status = 4;
   */
  consensusStatus?: ConsensusStatus;

  constructor(data?: PartialMessage<Block>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.Block";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "header", kind: "message", T: BlockHeader },
    { no: 2, name: "footer", kind: "message", T: BlockFooter, opt: true },
    { no: 3, name: "body", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true },
    { no: 4, name: "consensus_status", kind: "enum", T: proto3.getEnumType(ConsensusStatus), opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Block {
    return new Block().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Block {
    return new Block().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Block {
    return new Block().fromJsonString(jsonString, options);
  }

  static equals(a: Block | PlainMessage<Block> | undefined, b: Block | PlainMessage<Block> | undefined): boolean {
    return proto3.util.equals(Block, a, b);
  }
}

/**
 * RawBlock captures raw block bytes for direct access.
 *
 * @generated from message thru.core.v1.RawBlock
 */
export class RawBlock extends Message<RawBlock> {
  /**
   * @generated from field: uint64 slot = 1;
   */
  slot = protoInt64.zero;

  /**
   * @generated from field: bytes raw_block = 2;
   */
  rawBlock = new Uint8Array(0);

  constructor(data?: PartialMessage<RawBlock>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.RawBlock";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "slot", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "raw_block", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RawBlock {
    return new RawBlock().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RawBlock {
    return new RawBlock().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RawBlock {
    return new RawBlock().fromJsonString(jsonString, options);
  }

  static equals(a: RawBlock | PlainMessage<RawBlock> | undefined, b: RawBlock | PlainMessage<RawBlock> | undefined): boolean {
    return proto3.util.equals(RawBlock, a, b);
  }
}

