// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file thru/core/v1/state.proto (package thru.core.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Pubkey } from "../../common/v1/primitives_pb";

/**
 * StateProofType selects the type of state proof to generate.
 *
 * @generated from enum thru.core.v1.StateProofType
 */
export enum StateProofType {
  /**
   * @generated from enum value: STATE_PROOF_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATE_PROOF_TYPE_CREATING = 1;
   */
  CREATING = 1,

  /**
   * @generated from enum value: STATE_PROOF_TYPE_UPDATING = 2;
   */
  UPDATING = 2,

  /**
   * @generated from enum value: STATE_PROOF_TYPE_EXISTING = 3;
   */
  EXISTING = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(StateProofType)
proto3.util.setEnumType(StateProofType, "thru.core.v1.StateProofType", [
  { no: 0, name: "STATE_PROOF_TYPE_UNSPECIFIED" },
  { no: 1, name: "STATE_PROOF_TYPE_CREATING" },
  { no: 2, name: "STATE_PROOF_TYPE_UPDATING" },
  { no: 3, name: "STATE_PROOF_TYPE_EXISTING" },
]);

/**
 * StateProofRequest describes a request to generate an account state proof.
 *
 * @generated from message thru.core.v1.StateProofRequest
 */
export class StateProofRequest extends Message<StateProofRequest> {
  /**
   * @generated from field: thru.common.v1.Pubkey address = 1;
   */
  address?: Pubkey;

  /**
   * @generated from field: thru.core.v1.StateProofType proof_type = 2;
   */
  proofType = StateProofType.UNSPECIFIED;

  /**
   * @generated from field: optional uint64 target_slot = 3;
   */
  targetSlot?: bigint;

  constructor(data?: PartialMessage<StateProofRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.StateProofRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "address", kind: "message", T: Pubkey },
    { no: 2, name: "proof_type", kind: "enum", T: proto3.getEnumType(StateProofType) },
    { no: 3, name: "target_slot", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StateProofRequest {
    return new StateProofRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StateProofRequest {
    return new StateProofRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StateProofRequest {
    return new StateProofRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StateProofRequest | PlainMessage<StateProofRequest> | undefined, b: StateProofRequest | PlainMessage<StateProofRequest> | undefined): boolean {
    return proto3.util.equals(StateProofRequest, a, b);
  }
}

/**
 * StateProof returns binary proof data along with context.
 *
 * @generated from message thru.core.v1.StateProof
 */
export class StateProof extends Message<StateProof> {
  /**
   * @generated from field: bytes proof = 1;
   */
  proof = new Uint8Array(0);

  /**
   * @generated from field: uint64 slot = 2;
   */
  slot = protoInt64.zero;

  constructor(data?: PartialMessage<StateProof>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.StateProof";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "proof", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "slot", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StateProof {
    return new StateProof().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StateProof {
    return new StateProof().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StateProof {
    return new StateProof().fromJsonString(jsonString, options);
  }

  static equals(a: StateProof | PlainMessage<StateProof> | undefined, b: StateProof | PlainMessage<StateProof> | undefined): boolean {
    return proto3.util.equals(StateProof, a, b);
  }
}

