// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file thru/core/v1/transaction.proto (package thru.core.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Pubkey, Signature } from "../../common/v1/primitives_pb";

/**
 * TransactionView controls how transactions are materialized in responses.
 *
 * @generated from enum thru.core.v1.TransactionView
 */
export enum TransactionView {
  /**
   * @generated from enum value: TRANSACTION_VIEW_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TRANSACTION_VIEW_SIGNATURE_ONLY = 1;
   */
  SIGNATURE_ONLY = 1,

  /**
   * @generated from enum value: TRANSACTION_VIEW_HEADER_ONLY = 2;
   */
  HEADER_ONLY = 2,

  /**
   * @generated from enum value: TRANSACTION_VIEW_HEADER_AND_BODY = 3;
   */
  HEADER_AND_BODY = 3,

  /**
   * @generated from enum value: TRANSACTION_VIEW_FULL = 4;
   */
  FULL = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(TransactionView)
proto3.util.setEnumType(TransactionView, "thru.core.v1.TransactionView", [
  { no: 0, name: "TRANSACTION_VIEW_UNSPECIFIED" },
  { no: 1, name: "TRANSACTION_VIEW_SIGNATURE_ONLY" },
  { no: 2, name: "TRANSACTION_VIEW_HEADER_ONLY" },
  { no: 3, name: "TRANSACTION_VIEW_HEADER_AND_BODY" },
  { no: 4, name: "TRANSACTION_VIEW_FULL" },
]);

/**
 * TransactionVmError enumerates runtime error codes returned by the executor.
 *
 * @generated from enum thru.core.v1.TransactionVmError
 */
export enum TransactionVmError {
  /**
   * TN_RUNTIME_TXN_EXECUTE_SUCCESS
   *
   * @generated from enum value: TRANSACTION_VM_EXECUTE_SUCCESS = 0;
   */
  TRANSACTION_VM_EXECUTE_SUCCESS = 0,

  /**
   * TN_RUNTIME_TXN_ERR_INVALID_FORMAT
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_INVALID_FORMAT = -255;
   */
  TRANSACTION_VM_ERROR_INVALID_FORMAT = -255,

  /**
   * TN_RUNTIME_TXN_ERR_INVALID_VERSION
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_INVALID_VERSION = -254;
   */
  TRANSACTION_VM_ERROR_INVALID_VERSION = -254,

  /**
   * TN_RUNTIME_TXN_ERR_INVALID_FLAGS
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_INVALID_FLAGS = -253;
   */
  TRANSACTION_VM_ERROR_INVALID_FLAGS = -253,

  /**
   * TN_RUNTIME_TXN_ERR_INVALID_SIGNATURE
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_INVALID_SIGNATURE = -252;
   */
  TRANSACTION_VM_ERROR_INVALID_SIGNATURE = -252,

  /**
   * TN_RUNTIME_TXN_ERR_DUPLICATE_ACCOUNT
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_DUPLICATE_ACCOUNT = -251;
   */
  TRANSACTION_VM_ERROR_DUPLICATE_ACCOUNT = -251,

  /**
   * TN_RUNTIME_TXN_ERR_UNSORTED_ACCOUNTS
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_UNSORTED_ACCOUNTS = -250;
   */
  TRANSACTION_VM_ERROR_UNSORTED_ACCOUNTS = -250,

  /**
   * TN_RUNTIME_TXN_ERR_UNSORTED_READWRITE_ACCOUNTS
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_UNSORTED_READWRITE_ACCOUNTS = -249;
   */
  TRANSACTION_VM_ERROR_UNSORTED_READWRITE_ACCOUNTS = -249,

  /**
   * TN_RUNTIME_TXN_ERR_UNSORTED_READONLY_ACCOUNTS
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_UNSORTED_READONLY_ACCOUNTS = -248;
   */
  TRANSACTION_VM_ERROR_UNSORTED_READONLY_ACCOUNTS = -248,

  /**
   * TN_RUNTIME_TXN_ERR_ACCOUNT_COUNT_LIMIT_EXCEEDED
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_ACCOUNT_COUNT_LIMIT_EXCEEDED = -247;
   */
  TRANSACTION_VM_ERROR_ACCOUNT_COUNT_LIMIT_EXCEEDED = -247,

  /**
   * TN_RUNTIME_TXN_ERR_NONCE_TOO_LOW
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_NONCE_TOO_LOW = -511;
   */
  TRANSACTION_VM_ERROR_NONCE_TOO_LOW = -511,

  /**
   * TN_RUNTIME_TXN_ERR_NONCE_TOO_HIGH
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_NONCE_TOO_HIGH = -510;
   */
  TRANSACTION_VM_ERROR_NONCE_TOO_HIGH = -510,

  /**
   * TN_RUNTIME_TXN_ERR_INSUFFICIENT_FEE_PAYER_BALANCE
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_INSUFFICIENT_FEE_PAYER_BALANCE = -509;
   */
  TRANSACTION_VM_ERROR_INSUFFICIENT_FEE_PAYER_BALANCE = -509,

  /**
   * TN_RUNTIME_TXN_ERR_FEE_PAYER_ACCOUNT_DOES_NOT_EXIST
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_FEE_PAYER_ACCOUNT_DOES_NOT_EXIST = -508;
   */
  TRANSACTION_VM_ERROR_FEE_PAYER_ACCOUNT_DOES_NOT_EXIST = -508,

  /**
   * TN_RUNTIME_TXN_ERR_NOT_LIVE_YET
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_NOT_LIVE_YET = -507;
   */
  TRANSACTION_VM_ERROR_NOT_LIVE_YET = -507,

  /**
   * TN_RUNTIME_TXN_ERR_EXPIRED
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_EXPIRED = -506;
   */
  TRANSACTION_VM_ERROR_EXPIRED = -506,

  /**
   * TN_RUNTIME_TXN_ERR_INVALID_FEE_PAYER_STATE_PROOF
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF = -505;
   */
  TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF = -505,

  /**
   * TN_RUNTIME_TXN_ERR_INVALID_FEE_PAYER_STATE_PROOF_TYPE
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF_TYPE = -504;
   */
  TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF_TYPE = -504,

  /**
   * TN_RUNTIME_TXN_ERR_INVALID_FEE_PAYER_STATE_PROOF_SLOT
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF_SLOT = -503;
   */
  TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF_SLOT = -503,

  /**
   * TN_RUNTIME_TXN_ERR_INVALID_FEE_PAYER_ACCOUNT_OWNER
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_ACCOUNT_OWNER = -502;
   */
  TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_ACCOUNT_OWNER = -502,

  /**
   * TN_RUNTIME_TXN_ERR_INVALID_FEE_PAYER_STATE_PROOF_ACCOUNT_OWNER
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF_ACCOUNT_OWNER = -501;
   */
  TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF_ACCOUNT_OWNER = -501,

  /**
   * TN_RUNTIME_TXN_ERR_INVALID_FEE_PAYER_STATE_PROOF_ACCOUNT_META_DATA_SZ
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF_ACCOUNT_META_DATA_SZ = -500;
   */
  TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF_ACCOUNT_META_DATA_SZ = -500,

  /**
   * TN_RUNTIME_TXN_ERR_VM_FAILED
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_VM_FAILED = -767;
   */
  TRANSACTION_VM_ERROR_VM_FAILED = -767,

  /**
   * TN_RUNTIME_TXN_ERR_INVALID_PROGRAM_ACCOUNT
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_INVALID_PROGRAM_ACCOUNT = -766;
   */
  TRANSACTION_VM_ERROR_INVALID_PROGRAM_ACCOUNT = -766,

  /**
   * TN_RUNTIME_TXN_ERR_VM_REVERT
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_VM_REVERT = -765;
   */
  TRANSACTION_VM_ERROR_VM_REVERT = -765,

  /**
   * TN_RUNTIME_TXN_ERR_CU_EXHAUSTED
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_CU_EXHAUSTED = -764;
   */
  TRANSACTION_VM_ERROR_CU_EXHAUSTED = -764,

  /**
   * TN_RUNTIME_TXN_ERR_SU_EXHAUSTED
   *
   * @generated from enum value: TRANSACTION_VM_ERROR_SU_EXHAUSTED = -763;
   */
  TRANSACTION_VM_ERROR_SU_EXHAUSTED = -763,
}
// Retrieve enum metadata with: proto3.getEnumType(TransactionVmError)
proto3.util.setEnumType(TransactionVmError, "thru.core.v1.TransactionVmError", [
  { no: 0, name: "TRANSACTION_VM_EXECUTE_SUCCESS" },
  { no: -255, name: "TRANSACTION_VM_ERROR_INVALID_FORMAT" },
  { no: -254, name: "TRANSACTION_VM_ERROR_INVALID_VERSION" },
  { no: -253, name: "TRANSACTION_VM_ERROR_INVALID_FLAGS" },
  { no: -252, name: "TRANSACTION_VM_ERROR_INVALID_SIGNATURE" },
  { no: -251, name: "TRANSACTION_VM_ERROR_DUPLICATE_ACCOUNT" },
  { no: -250, name: "TRANSACTION_VM_ERROR_UNSORTED_ACCOUNTS" },
  { no: -249, name: "TRANSACTION_VM_ERROR_UNSORTED_READWRITE_ACCOUNTS" },
  { no: -248, name: "TRANSACTION_VM_ERROR_UNSORTED_READONLY_ACCOUNTS" },
  { no: -247, name: "TRANSACTION_VM_ERROR_ACCOUNT_COUNT_LIMIT_EXCEEDED" },
  { no: -511, name: "TRANSACTION_VM_ERROR_NONCE_TOO_LOW" },
  { no: -510, name: "TRANSACTION_VM_ERROR_NONCE_TOO_HIGH" },
  { no: -509, name: "TRANSACTION_VM_ERROR_INSUFFICIENT_FEE_PAYER_BALANCE" },
  { no: -508, name: "TRANSACTION_VM_ERROR_FEE_PAYER_ACCOUNT_DOES_NOT_EXIST" },
  { no: -507, name: "TRANSACTION_VM_ERROR_NOT_LIVE_YET" },
  { no: -506, name: "TRANSACTION_VM_ERROR_EXPIRED" },
  { no: -505, name: "TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF" },
  { no: -504, name: "TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF_TYPE" },
  { no: -503, name: "TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF_SLOT" },
  { no: -502, name: "TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_ACCOUNT_OWNER" },
  { no: -501, name: "TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF_ACCOUNT_OWNER" },
  { no: -500, name: "TRANSACTION_VM_ERROR_INVALID_FEE_PAYER_STATE_PROOF_ACCOUNT_META_DATA_SZ" },
  { no: -767, name: "TRANSACTION_VM_ERROR_VM_FAILED" },
  { no: -766, name: "TRANSACTION_VM_ERROR_INVALID_PROGRAM_ACCOUNT" },
  { no: -765, name: "TRANSACTION_VM_ERROR_VM_REVERT" },
  { no: -764, name: "TRANSACTION_VM_ERROR_CU_EXHAUSTED" },
  { no: -763, name: "TRANSACTION_VM_ERROR_SU_EXHAUSTED" },
]);

/**
 * TransactionHeader carries structured metadata for a transaction.
 *
 * @generated from message thru.core.v1.TransactionHeader
 */
export class TransactionHeader extends Message<TransactionHeader> {
  /**
   * @generated from field: thru.common.v1.Signature fee_payer_signature = 1;
   */
  feePayerSignature?: Signature;

  /**
   * @generated from field: uint32 version = 2;
   */
  version = 0;

  /**
   * @generated from field: uint32 flags = 3;
   */
  flags = 0;

  /**
   * @generated from field: uint32 readwrite_accounts_count = 4;
   */
  readwriteAccountsCount = 0;

  /**
   * @generated from field: uint32 readonly_accounts_count = 5;
   */
  readonlyAccountsCount = 0;

  /**
   * @generated from field: uint32 instruction_data_size = 6;
   */
  instructionDataSize = 0;

  /**
   * @generated from field: uint32 requested_compute_units = 7;
   */
  requestedComputeUnits = 0;

  /**
   * @generated from field: uint32 requested_state_units = 8;
   */
  requestedStateUnits = 0;

  /**
   * @generated from field: uint32 requested_memory_units = 9;
   */
  requestedMemoryUnits = 0;

  /**
   * @generated from field: uint32 expiry_after = 10;
   */
  expiryAfter = 0;

  /**
   * @generated from field: uint64 fee = 11;
   */
  fee = protoInt64.zero;

  /**
   * @generated from field: uint64 nonce = 12;
   */
  nonce = protoInt64.zero;

  /**
   * @generated from field: uint64 start_slot = 13;
   */
  startSlot = protoInt64.zero;

  /**
   * @generated from field: thru.common.v1.Pubkey fee_payer_pubkey = 14;
   */
  feePayerPubkey?: Pubkey;

  /**
   * @generated from field: thru.common.v1.Pubkey program_pubkey = 15;
   */
  programPubkey?: Pubkey;

  constructor(data?: PartialMessage<TransactionHeader>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.TransactionHeader";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "fee_payer_signature", kind: "message", T: Signature },
    { no: 2, name: "version", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "flags", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "readwrite_accounts_count", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 5, name: "readonly_accounts_count", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 6, name: "instruction_data_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 7, name: "requested_compute_units", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 8, name: "requested_state_units", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 9, name: "requested_memory_units", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 10, name: "expiry_after", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 11, name: "fee", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 12, name: "nonce", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 13, name: "start_slot", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 14, name: "fee_payer_pubkey", kind: "message", T: Pubkey },
    { no: 15, name: "program_pubkey", kind: "message", T: Pubkey },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionHeader {
    return new TransactionHeader().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionHeader {
    return new TransactionHeader().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionHeader {
    return new TransactionHeader().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionHeader | PlainMessage<TransactionHeader> | undefined, b: TransactionHeader | PlainMessage<TransactionHeader> | undefined): boolean {
    return proto3.util.equals(TransactionHeader, a, b);
  }
}

/**
 * TransactionExecutionResult captures execution outcomes.
 *
 * @generated from message thru.core.v1.TransactionExecutionResult
 */
export class TransactionExecutionResult extends Message<TransactionExecutionResult> {
  /**
   * @generated from field: uint32 consumed_compute_units = 1;
   */
  consumedComputeUnits = 0;

  /**
   * @generated from field: uint32 consumed_memory_units = 2;
   */
  consumedMemoryUnits = 0;

  /**
   * @generated from field: uint32 consumed_state_units = 3;
   */
  consumedStateUnits = 0;

  /**
   * @generated from field: uint64 user_error_code = 4;
   */
  userErrorCode = protoInt64.zero;

  /**
   * @generated from field: thru.core.v1.TransactionVmError vm_error = 5;
   */
  vmError = TransactionVmError.TRANSACTION_VM_EXECUTE_SUCCESS;

  /**
   * @generated from field: uint64 execution_result = 6;
   */
  executionResult = protoInt64.zero;

  /**
   * @generated from field: uint32 pages_used = 7;
   */
  pagesUsed = 0;

  /**
   * @generated from field: uint32 events_count = 8;
   */
  eventsCount = 0;

  /**
   * @generated from field: uint32 events_size = 9;
   */
  eventsSize = 0;

  /**
   * @generated from field: repeated thru.common.v1.Pubkey readwrite_accounts = 10;
   */
  readwriteAccounts: Pubkey[] = [];

  /**
   * @generated from field: repeated thru.common.v1.Pubkey readonly_accounts = 11;
   */
  readonlyAccounts: Pubkey[] = [];

  /**
   * @generated from field: repeated thru.core.v1.TransactionEvent events = 12;
   */
  events: TransactionEvent[] = [];

  constructor(data?: PartialMessage<TransactionExecutionResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.TransactionExecutionResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "consumed_compute_units", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "consumed_memory_units", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "consumed_state_units", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "user_error_code", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "vm_error", kind: "enum", T: proto3.getEnumType(TransactionVmError) },
    { no: 6, name: "execution_result", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "pages_used", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 8, name: "events_count", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 9, name: "events_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 10, name: "readwrite_accounts", kind: "message", T: Pubkey, repeated: true },
    { no: 11, name: "readonly_accounts", kind: "message", T: Pubkey, repeated: true },
    { no: 12, name: "events", kind: "message", T: TransactionEvent, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionExecutionResult {
    return new TransactionExecutionResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionExecutionResult {
    return new TransactionExecutionResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionExecutionResult {
    return new TransactionExecutionResult().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionExecutionResult | PlainMessage<TransactionExecutionResult> | undefined, b: TransactionExecutionResult | PlainMessage<TransactionExecutionResult> | undefined): boolean {
    return proto3.util.equals(TransactionExecutionResult, a, b);
  }
}

/**
 * TransactionEvent describes an event emitted during transaction execution.
 *
 * @generated from message thru.core.v1.TransactionEvent
 */
export class TransactionEvent extends Message<TransactionEvent> {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId = "";

  /**
   * @generated from field: uint32 call_idx = 2;
   */
  callIdx = 0;

  /**
   * @generated from field: uint32 program_idx = 3;
   */
  programIdx = 0;

  /**
   * @generated from field: thru.common.v1.Pubkey program = 4;
   */
  program?: Pubkey;

  /**
   * @generated from field: bytes payload = 5;
   */
  payload = new Uint8Array(0);

  constructor(data?: PartialMessage<TransactionEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.TransactionEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "call_idx", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "program_idx", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "program", kind: "message", T: Pubkey },
    { no: 5, name: "payload", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionEvent {
    return new TransactionEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionEvent {
    return new TransactionEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionEvent {
    return new TransactionEvent().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionEvent | PlainMessage<TransactionEvent> | undefined, b: TransactionEvent | PlainMessage<TransactionEvent> | undefined): boolean {
    return proto3.util.equals(TransactionEvent, a, b);
  }
}

/**
 * Transaction describes a fully decoded transaction resource.
 *
 * @generated from message thru.core.v1.Transaction
 */
export class Transaction extends Message<Transaction> {
  /**
   * @generated from field: thru.common.v1.Signature signature = 1;
   */
  signature?: Signature;

  /**
   * @generated from field: thru.core.v1.TransactionHeader header = 2;
   */
  header?: TransactionHeader;

  /**
   * @generated from field: optional bytes body = 3;
   */
  body?: Uint8Array;

  /**
   * @generated from field: optional thru.core.v1.TransactionExecutionResult execution_result = 4;
   */
  executionResult?: TransactionExecutionResult;

  /**
   * @generated from field: optional uint64 slot = 5;
   */
  slot?: bigint;

  /**
   * @generated from field: optional uint32 block_offset = 6;
   */
  blockOffset?: number;

  constructor(data?: PartialMessage<Transaction>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.Transaction";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "signature", kind: "message", T: Signature },
    { no: 2, name: "header", kind: "message", T: TransactionHeader },
    { no: 3, name: "body", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true },
    { no: 4, name: "execution_result", kind: "message", T: TransactionExecutionResult, opt: true },
    { no: 5, name: "slot", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 6, name: "block_offset", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction {
    return new Transaction().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction {
    return new Transaction().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction {
    return new Transaction().fromJsonString(jsonString, options);
  }

  static equals(a: Transaction | PlainMessage<Transaction> | undefined, b: Transaction | PlainMessage<Transaction> | undefined): boolean {
    return proto3.util.equals(Transaction, a, b);
  }
}

/**
 * RawTransaction provides direct access to serialized transaction bytes.
 *
 * @generated from message thru.core.v1.RawTransaction
 */
export class RawTransaction extends Message<RawTransaction> {
  /**
   * @generated from field: thru.common.v1.Signature signature = 1;
   */
  signature?: Signature;

  /**
   * @generated from field: bytes raw_transaction = 2;
   */
  rawTransaction = new Uint8Array(0);

  constructor(data?: PartialMessage<RawTransaction>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.core.v1.RawTransaction";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "signature", kind: "message", T: Signature },
    { no: 2, name: "raw_transaction", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RawTransaction {
    return new RawTransaction().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RawTransaction {
    return new RawTransaction().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RawTransaction {
    return new RawTransaction().fromJsonString(jsonString, options);
  }

  static equals(a: RawTransaction | PlainMessage<RawTransaction> | undefined, b: RawTransaction | PlainMessage<RawTransaction> | undefined): boolean {
    return proto3.util.equals(RawTransaction, a, b);
  }
}

