# Simple makefile for my Thru project

BASEDIR:=$(CURDIR)/build
# Set THRU_C_SDK_DIR to the location of the built SDK (where include/ and lib/ are)
THRU_C_SDK_DIR:=$(CURDIR)/../../sdks/c/build/thruvm
# Include the program makefile from the SDK source directory
include $(CURDIR)/../../sdks/c/thru-sdk/thru_c_program.mk
