// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file thru/common/v1/filters.proto (package thru.common.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Pubkey, Signature, TaPubkey, TsSignature } from "./primitives_pb";

/**
 * Filter represents a CEL-based expression applied to query or stream results.
 *
 * @generated from message thru.common.v1.Filter
 */
export class Filter extends Message<Filter> {
  /**
   * CEL expression applied server-side. Empty expressions are treated as no-op.
   *
   * @generated from field: optional string expression = 1;
   */
  expression?: string;

  /**
   * Named parameter bindings for expression parameterization.
   *
   * @generated from field: map<string, thru.common.v1.FilterParamValue> params = 2;
   */
  params: { [key: string]: FilterParamValue } = {};

  constructor(data?: PartialMessage<Filter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.common.v1.Filter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "expression", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "params", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: FilterParamValue} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Filter {
    return new Filter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Filter {
    return new Filter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Filter {
    return new Filter().fromJsonString(jsonString, options);
  }

  static equals(a: Filter | PlainMessage<Filter> | undefined, b: Filter | PlainMessage<Filter> | undefined): boolean {
    return proto3.util.equals(Filter, a, b);
  }
}

/**
 * FilterParamValue carries strongly-typed CEL parameter bindings.
 *
 * @generated from message thru.common.v1.FilterParamValue
 */
export class FilterParamValue extends Message<FilterParamValue> {
  /**
   * @generated from oneof thru.common.v1.FilterParamValue.kind
   */
  kind: {
    /**
     * @generated from field: string string_value = 1;
     */
    value: string;
    case: "stringValue";
  } | {
    /**
     * @generated from field: bytes bytes_value = 2;
     */
    value: Uint8Array;
    case: "bytesValue";
  } | {
    /**
     * @generated from field: bool bool_value = 3;
     */
    value: boolean;
    case: "boolValue";
  } | {
    /**
     * @generated from field: sint64 int_value = 4;
     */
    value: bigint;
    case: "intValue";
  } | {
    /**
     * @generated from field: uint64 uint_value = 5;
     */
    value: bigint;
    case: "uintValue";
  } | {
    /**
     * @generated from field: double double_value = 6;
     */
    value: number;
    case: "doubleValue";
  } | {
    /**
     * @generated from field: thru.common.v1.Pubkey pubkey_value = 7;
     */
    value: Pubkey;
    case: "pubkeyValue";
  } | {
    /**
     * @generated from field: thru.common.v1.Signature signature_value = 8;
     */
    value: Signature;
    case: "signatureValue";
  } | {
    /**
     * @generated from field: thru.common.v1.TaPubkey ta_pubkey_value = 9;
     */
    value: TaPubkey;
    case: "taPubkeyValue";
  } | {
    /**
     * @generated from field: thru.common.v1.TsSignature ts_signature_value = 10;
     */
    value: TsSignature;
    case: "tsSignatureValue";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<FilterParamValue>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.common.v1.FilterParamValue";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "string_value", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "kind" },
    { no: 2, name: "bytes_value", kind: "scalar", T: 12 /* ScalarType.BYTES */, oneof: "kind" },
    { no: 3, name: "bool_value", kind: "scalar", T: 8 /* ScalarType.BOOL */, oneof: "kind" },
    { no: 4, name: "int_value", kind: "scalar", T: 18 /* ScalarType.SINT64 */, oneof: "kind" },
    { no: 5, name: "uint_value", kind: "scalar", T: 4 /* ScalarType.UINT64 */, oneof: "kind" },
    { no: 6, name: "double_value", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, oneof: "kind" },
    { no: 7, name: "pubkey_value", kind: "message", T: Pubkey, oneof: "kind" },
    { no: 8, name: "signature_value", kind: "message", T: Signature, oneof: "kind" },
    { no: 9, name: "ta_pubkey_value", kind: "message", T: TaPubkey, oneof: "kind" },
    { no: 10, name: "ts_signature_value", kind: "message", T: TsSignature, oneof: "kind" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FilterParamValue {
    return new FilterParamValue().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FilterParamValue {
    return new FilterParamValue().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FilterParamValue {
    return new FilterParamValue().fromJsonString(jsonString, options);
  }

  static equals(a: FilterParamValue | PlainMessage<FilterParamValue> | undefined, b: FilterParamValue | PlainMessage<FilterParamValue> | undefined): boolean {
    return proto3.util.equals(FilterParamValue, a, b);
  }
}

/**
 * CelFilterValidation describes the validation configuration returned to
 * clients to help them build safe filter expressions.
 *
 * @generated from message thru.common.v1.CelFilterValidation
 */
export class CelFilterValidation extends Message<CelFilterValidation> {
  /**
   * List of allowed CEL function names for a specific request type.
   *
   * @generated from field: repeated string allowed_functions = 1;
   */
  allowedFunctions: string[] = [];

  /**
   * List of allowed field names accessible to the CEL expression.
   *
   * @generated from field: repeated string allowed_fields = 2;
   */
  allowedFields: string[] = [];

  /**
   * Maximum AST node count permitted for a CEL expression.
   *
   * @generated from field: optional uint32 max_complexity = 3;
   */
  maxComplexity?: number;

  constructor(data?: PartialMessage<CelFilterValidation>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.common.v1.CelFilterValidation";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "allowed_functions", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "allowed_fields", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "max_complexity", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CelFilterValidation {
    return new CelFilterValidation().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CelFilterValidation {
    return new CelFilterValidation().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CelFilterValidation {
    return new CelFilterValidation().fromJsonString(jsonString, options);
  }

  static equals(a: CelFilterValidation | PlainMessage<CelFilterValidation> | undefined, b: CelFilterValidation | PlainMessage<CelFilterValidation> | undefined): boolean {
    return proto3.util.equals(CelFilterValidation, a, b);
  }
}

