// Generated by programs/bootstrap/generate-addresses.ts; do not edit.
export const EOA_PROGRAM_ID = "taEOAD2uLK1SLzPgtabFLUAx22yDlBs9DE9nZFTOESIGRr";
export const ROOT_MANAGER_PROGRAM_ADDRESS = "taAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEB";
export const MANAGER_PROGRAM_ADDRESS = "taMGRmPoSTkUtF6UlmCIq58K8OYsnXshOMPdobxxHytqmu";
export const UPLOADER_PROGRAM_ADDRESS = "taUPLMH5QYOAT4ktwQeO7DXAEKtqBhYehalNGf5BJFQDYq";
// Test fixture only: upload explicitly before use; absent from genesis.
export const SYSTEM_TEST_PROGRAM_ADDRESS = "tar71GzddPShylAkcr4uvCDLRtdovGCI64b54CYtqCWSVA";
export const NOOP_PROGRAM_ADDRESS = "taNOOPV4A7S3WTsirr149To2GoGZ9q8zllQaBrbekHfkJT";
export const ABI_MANAGER_PROGRAM_ADDRESS = "taABII8WXcPaPIt47cXjOBbyoBUGBDXznAMHorVMeok3mw";
export const TOKEN_PROGRAM_ADDRESS = "taTOKENKRgcl3vO0yVhftATDbXuhgWcfaaxv9xpEEdMdUE";
export const MULTICALL_PROGRAM_ADDRESS = "taMULTIrOL8WpIFr16C1ECsO60qAsuwmwJephZHDOTvSeP";
