// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file thru/services/v1/command_service.proto (package thru.services.v1, edition 2023)
// option features.field_presence = EXPLICIT;
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import { file_google_api_client } from "../../../google/api/client_pb";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import { file_thru_core_v1_transaction } from "../../core/v1/transaction_pb";
import type { Signature } from "../../core/v1/types_pb";
import { file_thru_core_v1_types } from "../../core/v1/types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file thru/services/v1/command_service.proto.
 */
export const file_thru_services_v1_command_service: GenFile = /*@__PURE__*/
  fileDesc("CiZ0aHJ1L3NlcnZpY2VzL3YxL2NvbW1hbmRfc2VydmljZS5wcm90bxIQdGhydS5zZXJ2aWNlcy52MSI2ChZTZW5kVHJhbnNhY3Rpb25SZXF1ZXN0EhwKD3Jhd190cmFuc2FjdGlvbhgBIAEoDEID4EECIkoKF1NlbmRUcmFuc2FjdGlvblJlc3BvbnNlEi8KCXNpZ25hdHVyZRgBIAEoCzIXLnRocnUuY29yZS52MS5TaWduYXR1cmVCA+BBAjKrAQoOQ29tbWFuZFNlcnZpY2USgwEKD1NlbmRUcmFuc2FjdGlvbhIoLnRocnUuc2VydmljZXMudjEuU2VuZFRyYW5zYWN0aW9uUmVxdWVzdBopLnRocnUuc2VydmljZXMudjEuU2VuZFRyYW5zYWN0aW9uUmVzcG9uc2UiG4LT5JMCFToBKiIQL3YxL3RyYW5zYWN0aW9ucxoTykEQYXBpLnRocnUubmV0d29ya0LjAQoUY29tLnRocnUuc2VydmljZXMudjFCE0NvbW1hbmRTZXJ2aWNlUHJvdG9QAVpIZ2l0aHViLmNvbS9VbnRvLUxhYnMvdGhydS1uZXQvZ3JwYy9wa2cvcHJvdG8vdGhydS9zZXJ2aWNlcy92MTtzZXJ2aWNlc3YxogIDVFNYqgIQVGhydS5TZXJ2aWNlcy5WMboCBFRIVVPKAhBUaHJ1XFNlcnZpY2VzXFYx4gIcVGhydVxTZXJ2aWNlc1xWMVxHUEJNZXRhZGF0YeoCElRocnU6OlNlcnZpY2VzOjpWMZIDAggBYghlZGl0aW9uc3DoBw", [file_google_api_annotations, file_google_api_client, file_google_api_field_behavior, file_thru_core_v1_transaction, file_thru_core_v1_types]);

/**
 * SendTransactionRequest submits a transaction to the cluster.
 *
 * @generated from message thru.services.v1.SendTransactionRequest
 */
export type SendTransactionRequest = Message<"thru.services.v1.SendTransactionRequest"> & {
  /**
   * Raw transaction bytes encoded according to chain specification.
   *
   * @generated from field: bytes raw_transaction = 1;
   */
  rawTransaction: Uint8Array;
};

/**
 * Describes the message thru.services.v1.SendTransactionRequest.
 * Use `create(SendTransactionRequestSchema)` to create a new message.
 */
export const SendTransactionRequestSchema: GenMessage<SendTransactionRequest> = /*@__PURE__*/
  messageDesc(file_thru_services_v1_command_service, 0);

/**
 * SendTransactionResponse echoes submission metadata.
 *
 * @generated from message thru.services.v1.SendTransactionResponse
 */
export type SendTransactionResponse = Message<"thru.services.v1.SendTransactionResponse"> & {
  /**
   * @generated from field: thru.core.v1.Signature signature = 1;
   */
  signature?: Signature;
};

/**
 * Describes the message thru.services.v1.SendTransactionResponse.
 * Use `create(SendTransactionResponseSchema)` to create a new message.
 */
export const SendTransactionResponseSchema: GenMessage<SendTransactionResponse> = /*@__PURE__*/
  messageDesc(file_thru_services_v1_command_service, 1);

/**
 * CommandService defines transactional RPCs that mutate state or perform
 * expensive computations.
 *
 * @generated from service thru.services.v1.CommandService
 */
export const CommandService: GenService<{
  /**
   * Submit a new transaction to the cluster.
   *
   * @generated from rpc thru.services.v1.CommandService.SendTransaction
   */
  sendTransaction: {
    methodKind: "unary";
    input: typeof SendTransactionRequestSchema;
    output: typeof SendTransactionResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_thru_services_v1_command_service, 0);

