// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file thru/core/v1/types.proto (package thru.core.v1, edition 2023)
// option features.field_presence = EXPLICIT;
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file thru/core/v1/types.proto.
 */
export const file_thru_core_v1_types: GenFile = /*@__PURE__*/
  fileDesc("Chh0aHJ1L2NvcmUvdjEvdHlwZXMucHJvdG8SDHRocnUuY29yZS52MSIjCgZQdWJrZXkSGQoFdmFsdWUYASABKAxCCuBBArpIBHoCaCAiIQoESGFzaBIZCgV2YWx1ZRgBIAEoDEIK4EECukgEegJoICImCglCbG9ja0hhc2gSGQoFdmFsdWUYASABKAxCCuBBArpIBHoCaEAiJgoJU2lnbmF0dXJlEhkKBXZhbHVlGAEgASgMQgrgQQK6SAR6AmhAQr4BChBjb20udGhydS5jb3JlLnYxQgpUeXBlc1Byb3RvUAFaQGdpdGh1Yi5jb20vVW50by1MYWJzL3RocnUtbmV0L2dycGMvcGtnL3Byb3RvL3RocnUvY29yZS92MTtjb3JldjGiAgNUQ1iqAgxUaHJ1LkNvcmUuVjG6AgRUSFVDygIMVGhydVxDb3JlXFYx4gIYVGhydVxDb3JlXFYxXEdQQk1ldGFkYXRh6gIOVGhydTo6Q29yZTo6VjGSAwIIAWIIZWRpdGlvbnNw6Ac", [file_buf_validate_validate, file_google_api_field_behavior]);

/**
 * Pubkey represents a 32-byte public key value.
 *
 * @generated from message thru.core.v1.Pubkey
 */
export type Pubkey = Message<"thru.core.v1.Pubkey"> & {
  /**
   * 32-byte public key buffer.
   *
   * @generated from field: bytes value = 1;
   */
  value: Uint8Array;
};

/**
 * Describes the message thru.core.v1.Pubkey.
 * Use `create(PubkeySchema)` to create a new message.
 */
export const PubkeySchema: GenMessage<Pubkey> = /*@__PURE__*/
  messageDesc(file_thru_core_v1_types, 0);

/**
 * Hash represents a 32-byte hash value.
 *
 * @generated from message thru.core.v1.Hash
 */
export type Hash = Message<"thru.core.v1.Hash"> & {
  /**
   * 32-byte hash buffer.
   *
   * @generated from field: bytes value = 1;
   */
  value: Uint8Array;
};

/**
 * Describes the message thru.core.v1.Hash.
 * Use `create(HashSchema)` to create a new message.
 */
export const HashSchema: GenMessage<Hash> = /*@__PURE__*/
  messageDesc(file_thru_core_v1_types, 1);

/**
 * BlockHash represents a 64-byte hash for block identifiers.
 *
 * @generated from message thru.core.v1.BlockHash
 */
export type BlockHash = Message<"thru.core.v1.BlockHash"> & {
  /**
   * 64-byte block hash buffer.
   *
   * @generated from field: bytes value = 1;
   */
  value: Uint8Array;
};

/**
 * Describes the message thru.core.v1.BlockHash.
 * Use `create(BlockHashSchema)` to create a new message.
 */
export const BlockHashSchema: GenMessage<BlockHash> = /*@__PURE__*/
  messageDesc(file_thru_core_v1_types, 2);

/**
 * Signature represents a 64-byte signature value.
 *
 * @generated from message thru.core.v1.Signature
 */
export type Signature = Message<"thru.core.v1.Signature"> & {
  /**
   * 64-byte signature buffer.
   *
   * @generated from field: bytes value = 1;
   */
  value: Uint8Array;
};

/**
 * Describes the message thru.core.v1.Signature.
 * Use `create(SignatureSchema)` to create a new message.
 */
export const SignatureSchema: GenMessage<Signature> = /*@__PURE__*/
  messageDesc(file_thru_core_v1_types, 3);

