// Generated by scripts/gen-feature-gate-registry.py. Do not edit.
pub const PARALLEL_EXEC_INDEX: u32 = 0;
pub const COMPRESSED_ACCOUNT_GROWTH_V2_INDEX: u32 = 1;
pub const MAX_COMPUTE_UNITS_PER_TXN_INDEX: u32 = 2;
pub const MAX_STATE_UNITS_PER_BLOCK_INDEX: u32 = 3;
pub const MAX_ACTIVE_STATE_UNITS_INDEX: u32 = 4;
pub const COMPRESS_BASELINE_UNITS_INDEX: u32 = 5;
pub const COMPRESS_HALVING_STEP_UNITS_INDEX: u32 = 6;
