// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file thru/common/v1/consensus.proto (package thru.common.v1, edition 2023)
// option features.field_presence = EXPLICIT;
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file thru/common/v1/consensus.proto.
 */
export const file_thru_common_v1_consensus: GenFile = /*@__PURE__*/
  fileDesc("Ch50aHJ1L2NvbW1vbi92MS9jb25zZW5zdXMucHJvdG8SDnRocnUuY29tbW9uLnYxIoIDCg5WZXJzaW9uQ29udGV4dBI2CgdjdXJyZW50GAEgASgLMh4udGhydS5jb21tb24udjEuQ3VycmVudFZlcnNpb25CA+BBAUgAEk4KE2N1cnJlbnRPckhpc3RvcmljYWwYAiABKAsyKi50aHJ1LmNvbW1vbi52MS5DdXJyZW50T3JIaXN0b3JpY2FsVmVyc2lvbkID4EEBSAASEwoEc2xvdBgDIAEoBEID4EEBSAASNAoJdGltZXN0YW1wGAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEID4EEBSAA6kQG6SI0BGooBChx2ZXJzaW9uX2NvbnRleHRfaGFzX3NlbGVjdG9yEi5vbmUgb2YgY3VycmVudCwgc2xvdCwgb3IgdGltZXN0YW1wIG11c3QgYmUgc2V0GjpoYXModGhpcy5jdXJyZW50KSB8fCBoYXModGhpcy5zbG90KSB8fCBoYXModGhpcy50aW1lc3RhbXApQgkKB3ZlcnNpb24iEAoOQ3VycmVudFZlcnNpb24iHAoaQ3VycmVudE9ySGlzdG9yaWNhbFZlcnNpb24q3wEKD0NvbnNlbnN1c1N0YXR1cxIgChxDT05TRU5TVVNfU1RBVFVTX1VOU1BFQ0lGSUVEEAASHQoZQ09OU0VOU1VTX1NUQVRVU19PQlNFUlZFRBABEh0KGUNPTlNFTlNVU19TVEFUVVNfSU5DTFVERUQQAhIeChpDT05TRU5TVVNfU1RBVFVTX0ZJTkFMSVpFRBADEiUKIUNPTlNFTlNVU19TVEFUVVNfTE9DQUxMWV9FWEVDVVRFRBAEEiUKIUNPTlNFTlNVU19TVEFUVVNfQ0xVU1RFUl9FWEVDVVRFRBAFQs8BChJjb20udGhydS5jb21tb24udjFCDkNvbnNlbnN1c1Byb3RvUAFaRGdpdGh1Yi5jb20vVW50by1MYWJzL3RocnUtbmV0L2dycGMvcGtnL3Byb3RvL3RocnUvY29tbW9uL3YxO2NvbW1vbnYxogIDVENYqgIOVGhydS5Db21tb24uVjG6AgNUSFXKAg5UaHJ1XENvbW1vblxWMeICGlRocnVcQ29tbW9uXFYxXEdQQk1ldGFkYXRh6gIQVGhydTo6Q29tbW9uOjpWMZIDAggBYghlZGl0aW9uc3DoBw", [file_buf_validate_validate, file_google_api_field_behavior, file_google_protobuf_timestamp]);

/**
 * VersionContext selects which logical version of a resource should be
 * returned. At least one field must be set.
 *
 * @generated from message thru.common.v1.VersionContext
 */
export type VersionContext = Message<"thru.common.v1.VersionContext"> & {
  /**
   * Specifies the desired version semantics.
   *
   * @generated from oneof thru.common.v1.VersionContext.version
   */
  version: {
    /**
     * Request the latest version available at request time.
     *
     * @generated from field: thru.common.v1.CurrentVersion current = 1;
     */
    value: CurrentVersion;
    case: "current";
  } | {
    /**
     * Request the latest version, or historical on.
     *
     * @generated from field: thru.common.v1.CurrentOrHistoricalVersion currentOrHistorical = 2;
     */
    value: CurrentOrHistoricalVersion;
    case: "currentOrHistorical";
  } | {
    /**
     * Request the version for a specific slot number.
     *
     * @generated from field: uint64 slot = 3;
     */
    value: bigint;
    case: "slot";
  } | {
    /**
     * Request the version nearest to the provided block timestamp.
     *
     * @generated from field: google.protobuf.Timestamp timestamp = 4;
     */
    value: Timestamp;
    case: "timestamp";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message thru.common.v1.VersionContext.
 * Use `create(VersionContextSchema)` to create a new message.
 */
export const VersionContextSchema: GenMessage<VersionContext> = /*@__PURE__*/
  messageDesc(file_thru_common_v1_consensus, 0);

/**
 * CurrentVersion is an empty marker message for VersionContext.current.
 *
 * @generated from message thru.common.v1.CurrentVersion
 */
export type CurrentVersion = Message<"thru.common.v1.CurrentVersion"> & {
};

/**
 * Describes the message thru.common.v1.CurrentVersion.
 * Use `create(CurrentVersionSchema)` to create a new message.
 */
export const CurrentVersionSchema: GenMessage<CurrentVersion> = /*@__PURE__*/
  messageDesc(file_thru_common_v1_consensus, 1);

/**
 * CurrentOrHistoricalVersion is an empty marker message for VersionContext.current.
 *
 * @generated from message thru.common.v1.CurrentOrHistoricalVersion
 */
export type CurrentOrHistoricalVersion = Message<"thru.common.v1.CurrentOrHistoricalVersion"> & {
};

/**
 * Describes the message thru.common.v1.CurrentOrHistoricalVersion.
 * Use `create(CurrentOrHistoricalVersionSchema)` to create a new message.
 */
export const CurrentOrHistoricalVersionSchema: GenMessage<CurrentOrHistoricalVersion> = /*@__PURE__*/
  messageDesc(file_thru_common_v1_consensus, 2);

/**
 * ConsensusStatus represents the minimum consensus level a resource has
 * achieved when returned by the service.
 *
 * @generated from enum thru.common.v1.ConsensusStatus
 */
export enum ConsensusStatus {
  /**
   * CONSENSUS_STATUS_UNSPECIFIED indicates the consensus status is unknown.
   *
   * @generated from enum value: CONSENSUS_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * CONSENSUS_STATUS_OBSERVED indicates the resource has been observed but
   * not yet confirmed in a finalized block.
   *
   * @generated from enum value: CONSENSUS_STATUS_OBSERVED = 1;
   */
  OBSERVED = 1,

  /**
   * CONSENSUS_STATUS_INCLUDED indicates the resource has been included in the
   * ledger but may not be finalized.
   *
   * @generated from enum value: CONSENSUS_STATUS_INCLUDED = 2;
   */
  INCLUDED = 2,

  /**
   * CONSENSUS_STATUS_FINALIZED indicates the resource is finalized for a slot.
   *
   * @generated from enum value: CONSENSUS_STATUS_FINALIZED = 3;
   */
  FINALIZED = 3,

  /**
   * CONSENSUS_STATUS_LOCALLY_EXECUTED indicates the local node executed the
   * resource but broader cluster finality may not have been achieved.
   *
   * @generated from enum value: CONSENSUS_STATUS_LOCALLY_EXECUTED = 4;
   */
  LOCALLY_EXECUTED = 4,

  /**
   * CONSENSUS_STATUS_CLUSTER_EXECUTED indicates the entire cluster has
   * executed and agreed on the resource.
   *
   * @generated from enum value: CONSENSUS_STATUS_CLUSTER_EXECUTED = 5;
   */
  CLUSTER_EXECUTED = 5,
}

/**
 * Describes the enum thru.common.v1.ConsensusStatus.
 */
export const ConsensusStatusSchema: GenEnum<ConsensusStatus> = /*@__PURE__*/
  enumDesc(file_thru_common_v1_consensus, 0);

