// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file thru/services/v1/command_service.proto (package thru.services.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3 } from "@bufbuild/protobuf";
import { Signature } from "../../common/v1/primitives_pb";
import { ConsensusStatus } from "../../common/v1/consensus_pb";
import { TransactionExecutionResult } from "../../core/v1/transaction_pb";

/**
 * SubmissionStatus represents the status of a transaction in the submission pipeline.
 *
 * @generated from enum thru.services.v1.SubmissionStatus
 */
export enum SubmissionStatus {
  /**
   * Submission status is unspecified (default value).
   *
   * @generated from enum value: SUBMISSION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Transaction has been received by the gRPC server.
   *
   * @generated from enum value: SUBMISSION_STATUS_RECEIVED = 1;
   */
  RECEIVED = 1,

  /**
   * Transaction has been accepted by the forwarder via UDS.
   *
   * @generated from enum value: SUBMISSION_STATUS_ACCEPTED = 2;
   */
  ACCEPTED = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(SubmissionStatus)
proto3.util.setEnumType(SubmissionStatus, "thru.services.v1.SubmissionStatus", [
  { no: 0, name: "SUBMISSION_STATUS_UNSPECIFIED" },
  { no: 1, name: "SUBMISSION_STATUS_RECEIVED" },
  { no: 2, name: "SUBMISSION_STATUS_ACCEPTED" },
]);

/**
 * SendTransactionRequest submits a transaction to the cluster.
 *
 * @generated from message thru.services.v1.SendTransactionRequest
 */
export class SendTransactionRequest extends Message<SendTransactionRequest> {
  /**
   * Raw transaction bytes encoded according to chain specification.
   *
   * @generated from field: bytes raw_transaction = 1;
   */
  rawTransaction = new Uint8Array(0);

  constructor(data?: PartialMessage<SendTransactionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.services.v1.SendTransactionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "raw_transaction", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendTransactionRequest {
    return new SendTransactionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendTransactionRequest {
    return new SendTransactionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendTransactionRequest {
    return new SendTransactionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SendTransactionRequest | PlainMessage<SendTransactionRequest> | undefined, b: SendTransactionRequest | PlainMessage<SendTransactionRequest> | undefined): boolean {
    return proto3.util.equals(SendTransactionRequest, a, b);
  }
}

/**
 * SendTransactionResponse echoes submission metadata.
 *
 * @generated from message thru.services.v1.SendTransactionResponse
 */
export class SendTransactionResponse extends Message<SendTransactionResponse> {
  /**
   * @generated from field: thru.common.v1.Signature signature = 1;
   */
  signature?: Signature;

  constructor(data?: PartialMessage<SendTransactionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.services.v1.SendTransactionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "signature", kind: "message", T: Signature },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendTransactionResponse {
    return new SendTransactionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendTransactionResponse {
    return new SendTransactionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendTransactionResponse {
    return new SendTransactionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SendTransactionResponse | PlainMessage<SendTransactionResponse> | undefined, b: SendTransactionResponse | PlainMessage<SendTransactionResponse> | undefined): boolean {
    return proto3.util.equals(SendTransactionResponse, a, b);
  }
}

/**
 * BatchSendTransactionsRequest submits multiple transactions to the cluster.
 *
 * @generated from message thru.services.v1.BatchSendTransactionsRequest
 */
export class BatchSendTransactionsRequest extends Message<BatchSendTransactionsRequest> {
  /**
   * List of raw transaction bytes encoded according to chain specification.
   *
   * @generated from field: repeated bytes raw_transactions = 1;
   */
  rawTransactions: Uint8Array[] = [];

  /**
   * Number of retries for each transaction if not accepted by UDS (defaults to 0).
   *
   * @generated from field: int32 num_retries = 2;
   */
  numRetries = 0;

  constructor(data?: PartialMessage<BatchSendTransactionsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.services.v1.BatchSendTransactionsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "raw_transactions", kind: "scalar", T: 12 /* ScalarType.BYTES */, repeated: true },
    { no: 2, name: "num_retries", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchSendTransactionsRequest {
    return new BatchSendTransactionsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchSendTransactionsRequest {
    return new BatchSendTransactionsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchSendTransactionsRequest {
    return new BatchSendTransactionsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: BatchSendTransactionsRequest | PlainMessage<BatchSendTransactionsRequest> | undefined, b: BatchSendTransactionsRequest | PlainMessage<BatchSendTransactionsRequest> | undefined): boolean {
    return proto3.util.equals(BatchSendTransactionsRequest, a, b);
  }
}

/**
 * BatchSendTransactionsResponse returns submission results for each transaction.
 *
 * @generated from message thru.services.v1.BatchSendTransactionsResponse
 */
export class BatchSendTransactionsResponse extends Message<BatchSendTransactionsResponse> {
  /**
   * Signatures for each transaction (in same order as request).
   *
   * @generated from field: repeated thru.common.v1.Signature signatures = 1;
   */
  signatures: Signature[] = [];

  /**
   * Acceptance status for each transaction (true if accepted, false if not).
   *
   * @generated from field: repeated bool accepted = 2;
   */
  accepted: boolean[] = [];

  constructor(data?: PartialMessage<BatchSendTransactionsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.services.v1.BatchSendTransactionsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "signatures", kind: "message", T: Signature, repeated: true },
    { no: 2, name: "accepted", kind: "scalar", T: 8 /* ScalarType.BOOL */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchSendTransactionsResponse {
    return new BatchSendTransactionsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchSendTransactionsResponse {
    return new BatchSendTransactionsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchSendTransactionsResponse {
    return new BatchSendTransactionsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: BatchSendTransactionsResponse | PlainMessage<BatchSendTransactionsResponse> | undefined, b: BatchSendTransactionsResponse | PlainMessage<BatchSendTransactionsResponse> | undefined): boolean {
    return proto3.util.equals(BatchSendTransactionsResponse, a, b);
  }
}

/**
 * SendAndTrackTxnRequest submits a transaction and tracks its execution.
 *
 * @generated from message thru.services.v1.SendAndTrackTxnRequest
 */
export class SendAndTrackTxnRequest extends Message<SendAndTrackTxnRequest> {
  /**
   * Raw transaction bytes encoded according to chain specification.
   *
   * @generated from field: bytes transaction = 1;
   */
  transaction = new Uint8Array(0);

  /**
   * Optional timeout for tracking the transaction execution.
   * If not specified, the stream will remain open until the transaction is executed or the client cancels.
   *
   * @generated from field: google.protobuf.Duration timeout = 2;
   */
  timeout?: Duration;

  constructor(data?: PartialMessage<SendAndTrackTxnRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.services.v1.SendAndTrackTxnRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "transaction", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "timeout", kind: "message", T: Duration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendAndTrackTxnRequest {
    return new SendAndTrackTxnRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendAndTrackTxnRequest {
    return new SendAndTrackTxnRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendAndTrackTxnRequest {
    return new SendAndTrackTxnRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SendAndTrackTxnRequest | PlainMessage<SendAndTrackTxnRequest> | undefined, b: SendAndTrackTxnRequest | PlainMessage<SendAndTrackTxnRequest> | undefined): boolean {
    return proto3.util.equals(SendAndTrackTxnRequest, a, b);
  }
}

/**
 * SendAndTrackTxnResponse streams transaction status updates.
 *
 * @generated from message thru.services.v1.SendAndTrackTxnResponse
 */
export class SendAndTrackTxnResponse extends Message<SendAndTrackTxnResponse> {
  /**
   * Current submission status of the transaction.
   *
   * @generated from field: thru.services.v1.SubmissionStatus status = 1;
   */
  status = SubmissionStatus.UNSPECIFIED;

  /**
   * Transaction signature (populated for tracking messages).
   *
   * @generated from field: thru.common.v1.Signature signature = 2;
   */
  signature?: Signature;

  /**
   * Consensus status (populated for tracking messages).
   *
   * @generated from field: thru.common.v1.ConsensusStatus consensus_status = 3;
   */
  consensusStatus = ConsensusStatus.UNSPECIFIED;

  /**
   * Execution result (populated for tracking messages when execution completes).
   *
   * @generated from field: thru.core.v1.TransactionExecutionResult execution_result = 4;
   */
  executionResult?: TransactionExecutionResult;

  constructor(data?: PartialMessage<SendAndTrackTxnResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "thru.services.v1.SendAndTrackTxnResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "enum", T: proto3.getEnumType(SubmissionStatus) },
    { no: 2, name: "signature", kind: "message", T: Signature },
    { no: 3, name: "consensus_status", kind: "enum", T: proto3.getEnumType(ConsensusStatus) },
    { no: 4, name: "execution_result", kind: "message", T: TransactionExecutionResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendAndTrackTxnResponse {
    return new SendAndTrackTxnResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendAndTrackTxnResponse {
    return new SendAndTrackTxnResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendAndTrackTxnResponse {
    return new SendAndTrackTxnResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SendAndTrackTxnResponse | PlainMessage<SendAndTrackTxnResponse> | undefined, b: SendAndTrackTxnResponse | PlainMessage<SendAndTrackTxnResponse> | undefined): boolean {
    return proto3.util.equals(SendAndTrackTxnResponse, a, b);
  }
}

