// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file thru/services/v1/command_service.proto (package thru.services.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BatchSendTransactionsRequest, BatchSendTransactionsResponse, SendAndTrackTxnRequest, SendAndTrackTxnResponse, SendTransactionRequest, SendTransactionResponse } from "./command_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * CommandService defines transactional RPCs that mutate state or perform
 * expensive computations.
 *
 * @generated from service thru.services.v1.CommandService
 */
export const CommandService = {
  typeName: "thru.services.v1.CommandService",
  methods: {
    /**
     * Submit a new transaction to the cluster.
     *
     * @generated from rpc thru.services.v1.CommandService.SendTransaction
     */
    sendTransaction: {
      name: "SendTransaction",
      I: SendTransactionRequest,
      O: SendTransactionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Submit multiple transactions to the cluster in batch.
     *
     * @generated from rpc thru.services.v1.CommandService.BatchSendTransactions
     */
    batchSendTransactions: {
      name: "BatchSendTransactions",
      I: BatchSendTransactionsRequest,
      O: BatchSendTransactionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Submit a transaction and track its execution status.
     * Returns a stream of status updates starting with RECEIVED, then ACCEPTED,
     * followed by consensus and execution updates, closing after the transaction is executed.
     *
     * @generated from rpc thru.services.v1.CommandService.SendAndTrackTxn
     */
    sendAndTrackTxn: {
      name: "SendAndTrackTxn",
      I: SendAndTrackTxnRequest,
      O: SendAndTrackTxnResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

