// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file thru/services/v1/streaming_service.proto (package thru.services.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { StreamAccountUpdatesRequest, StreamAccountUpdatesResponse, StreamBlocksRequest, StreamBlocksResponse, StreamEventsRequest, StreamEventsResponse, StreamHeightRequest, StreamHeightResponse, StreamTransactionsRequest, StreamTransactionsResponse, TrackTransactionRequest, TrackTransactionResponse } from "./streaming_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * StreamingService serves server-streaming gRPC APIs for real-time data.
 *
 * @generated from service thru.services.v1.StreamingService
 */
export const StreamingService = {
  typeName: "thru.services.v1.StreamingService",
  methods: {
    /**
     * @generated from rpc thru.services.v1.StreamingService.StreamBlocks
     */
    streamBlocks: {
      name: "StreamBlocks",
      I: StreamBlocksRequest,
      O: StreamBlocksResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc thru.services.v1.StreamingService.StreamAccountUpdates
     */
    streamAccountUpdates: {
      name: "StreamAccountUpdates",
      I: StreamAccountUpdatesRequest,
      O: StreamAccountUpdatesResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc thru.services.v1.StreamingService.StreamTransactions
     */
    streamTransactions: {
      name: "StreamTransactions",
      I: StreamTransactionsRequest,
      O: StreamTransactionsResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc thru.services.v1.StreamingService.StreamEvents
     */
    streamEvents: {
      name: "StreamEvents",
      I: StreamEventsRequest,
      O: StreamEventsResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc thru.services.v1.StreamingService.TrackTransaction
     */
    trackTransaction: {
      name: "TrackTransaction",
      I: TrackTransactionRequest,
      O: TrackTransactionResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc thru.services.v1.StreamingService.StreamHeight
     */
    streamHeight: {
      name: "StreamHeight",
      I: StreamHeightRequest,
      O: StreamHeightResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

