packages:
  - 'packages/*'
  - 'packages-private/*'
  - 'test-dapp'
  - 'explorer'
  - 'mint'
  - 'jcoin-app'
  - 'etl-bridge'
  - 'eve-token-app'
  - 'wallet-auth-manager'
  - 'wallet-keypair-manager'
  - 'chain-indexer'
  - '../mobile/passkey-demo-dapp'
  - 'wallet'
  - 'wallet/frontend/site'
  - 'wallet/frontend/mobile'
  - 'wallet/frontend/packages/*'
  - 'wallet/backend/apps/*'
  - 'wallet/backend/packages/*'
  - 'wallet/packages/*'
