packages:
  - 'packages/*'
  - 'packages-private/*'
  - 'wallet'
  - 'test-dapp'
  - 'explorer'
  - 'mint'
  - 'etl-bridge'
  - 'superapp-be'
  - 'eve-token-app'
  - 'wallet-auth-manager'
  - 'wallet-keypair-manager'
